# Generated by Django 3.2.5 on 2021-12-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='monto',
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(default=0)),
                ('cuentas', models.ManyToManyField(to='contabilidad.Cuenta')),
            ],
        ),
    ]
