# Generated by Django 3.2.5 on 2022-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('cbu', models.CharField(max_length=30)),
                ('tipo_empleo', models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], default='Publico', max_length=20)),
                ('ocupacion', models.CharField(max_length=30)),
                ('sueldo_bruto', models.FloatField(default=0)),
                ('situacion', models.CharField(choices=[('Activo', 'Con Credito Activo'), ('Sin Credito', 'Con Credito/s Finalizados'), ('En Juicio', 'En Gestion Judicial'), ('No Tuvo credito', 'Sin registro de creditos')], default='Activo', max_length=15)),
                ('bcra', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('embargo', models.BooleanField(default=False)),
                ('juicios', models.TextField(default='Sin juicios')),
                ('observacion', models.TextField(default='')),
            ],
        ),
    ]
