# Generated by Django 3.2.5 on 2021-07-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('cbu', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('situacion', models.CharField(choices=[('Activo', 'Con Credito Activo'), ('Sin Credito', 'Con Credito/s Finalizados'), ('En Juicio', 'En Gestion Judicial'), ('No Tuvo credito', 'Sin registro de creditos')], default='Activo', max_length=15)),
            ],
        ),
    ]
