# Generated by Django 3.2.5 on 2022-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bcra',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='embargo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='juicios',
            field=models.TextField(default='Sin juicios'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sueldo_bruto',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_empleo',
            field=models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], default='Publico', max_length=20),
        ),
    ]
