# Generated by Django 3.2.5 on 2021-07-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('monto', models.FloatField()),
                ('interes', models.FloatField()),
                ('cuotas', models.IntegerField()),
                ('mora', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('situacion', models.CharField(choices=[('ok', 'Al dia'), ('Mora Temprana', 'Atraso > 30 días'), ('Mora Tardia', 'Atraso > 90 dí as')], default='ok', max_length=15)),
            ],
        ),
    ]
