# Generated by Django 3.2.5 on 2021-10-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='situacion',
            field=models.CharField(choices=[('ok', 'Al dia'), ('Mora Temprana', 'Atraso entre 1 y 30 días'), ('Mora Tardia', 'Atraso > 30 días'), ('Situacion Judicial', 'Atraso > 90 días')], default='ok', max_length=20),
        ),
    ]
