# Generated by Django 3.2.5 on 2022-02-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mora',
            name='cargador_mora',
            field=models.CharField(choices=[('Franco', 'Franco'), ('Agustin', 'Agustin')], default='Franco', max_length=20, verbose_name='Cargó'),
        ),
        migrations.AddField(
            model_name='mora',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mora',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='situacion',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pago Pendiente'), ('Pago parcial', 'Pago Parcial'), ('No Pago', 'No Pago')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='mora',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mora_cuota', to='credito.cuota'),
        ),
    ]
