# Generated by Django 3.2.5 on 2022-02-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_auto_20220217_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mora',
            name='cuota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mora_cuota', to='credito.cuota'),
        ),
    ]
