# Generated by Django 3.2.5 on 2021-10-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_alter_credito_situacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='cuotas',
            new_name='cant_cuota',
        ),
        migrations.RenameField(
            model_name='credito',
            old_name='interes',
            new_name='capital',
        ),
        migrations.RenameField(
            model_name='credito',
            old_name='monto',
            new_name='monto_cuota',
        ),
        migrations.AddField(
            model_name='credito',
            name='tasa_interes',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
    ]
