# Generated by Django 3.2.5 on 2022-02-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_alter_mora_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mora',
            name='cuota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mora', to='credito.cuota'),
        ),
    ]
