# Generated by Django 3.2 on 2021-10-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0003_auto_20211008_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='monto_cuota',
            field=models.FloatField(default=0),
        ),
    ]
