# Generated by Django 3.2 on 2021-10-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_ocupacion'),
        ('credito', '0004_alter_credito_monto_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='titular',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente'),
        ),
    ]
