# Generated by Django 3.2 on 2021-10-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0005_credito_titular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('tasa', models.FloatField(default=0.15)),
                ('monto', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='credito',
            name='mora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credito.mora'),
        ),
    ]
