# Generated by Django 3.2 on 2021-10-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0006_auto_20211012_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mora',
            name='monto',
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_mora',
            field=models.FloatField(default=0),
        ),
    ]
