# Generated by Django 3.2 on 2021-10-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0007_auto_20211012_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='monto_cuota',
        ),
        migrations.AlterField(
            model_name='credito',
            name='mora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='credito.mora'),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente de Pago'), ('Vencido', 'Vencido')], default='Pendiente', max_length=30)),
                ('capital_amortizable', models.FloatField()),
                ('interes', models.FloatField()),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto_cuota', models.FloatField()),
                ('fecha_pago', models.DateField()),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credito.credito')),
            ],
        ),
    ]
