# Generated by Django 3.2.5 on 2021-10-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0008_auto_20211013_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='amortizacion',
            field=models.FloatField(default=0),
        ),
    ]
