# Generated by Django 3.2 on 2021-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0009_cuota_amortizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='mora_cuota',
            field=models.FloatField(default=0),
        ),
    ]
