# Generated by Django 3.2.5 on 2021-12-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0010_cuota_mora_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='situacion',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente de Pago'), ('Pago parcial', 'Pago Parcial'), ('No realizo Pago', 'No realizo Pago')], default='Pendiente', max_length=30),
        ),
    ]
