# Generated by Django 3.2.5 on 2022-02-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0012_auto_20220201_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credito_pago', to='credito.credito'),
        ),
    ]
