# Generated by Django 3.2.5 on 2022-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0013_alter_cuota_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='monto_cuota',
            field=models.FloatField(default=0),
        ),
    ]
