# Generated by Django 3.2.5 on 2021-12-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modelo', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('precioCompra', models.FloatField()),
                ('precioVenta', models.FloatField()),
                ('stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('operacion', models.CharField(choices=[{'Compra': 'Compra', 'Venta': 'Venta'}], max_length=10)),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('vehiculo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wolfmotors.vehiculo')),
            ],
        ),
    ]
