# Generated by Django 3.2.5 on 2022-02-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=150)),
                ('patente', models.CharField(default='AAA', max_length=100)),
                ('modelo', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('precio_mercado', models.FloatField(blank=True, null=True, verbose_name='Precio de Mercado')),
                ('stock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('operacion', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=10)),
                ('monto', models.FloatField()),
                ('descripcion', models.TextField(max_length=200)),
                ('responsable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.cobrador')),
                ('vehiculo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wolfmotors.vehiculo')),
            ],
        ),
    ]
