# Generated by Django 3.2.5 on 2021-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='operacion',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=10),
        ),
    ]
