# Generated by Django 3.2.5 on 2021-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0002_alter_operacion_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precioCompra',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precioVenta',
            field=models.FloatField(blank=True),
        ),
    ]
