# Generated by Django 3.2.5 on 2021-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0003_auto_20211220_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precioCompra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precioVenta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
