# Generated by Django 3.2.5 on 2021-12-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0007_auto_20211018_1127'),
        ('wolfmotors', '0004_auto_20211220_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.cobrador'),
        ),
    ]
