# Generated by Django 3.2.5 on 2021-12-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0005_operacion_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='precioCompra',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='precioVenta',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='precio_mercado',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio de Mercado'),
        ),
    ]
