# Generated by Django 3.2.5 on 2021-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0006_auto_20211220_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
