# Generated by Django 3.2.5 on 2021-12-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0007_auto_20211220_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='nombre',
            new_name='vehiculo',
        ),
    ]
