# Generated by Django 3.2.5 on 2021-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0008_rename_nombre_vehiculo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
