# Generated by Django 3.2.5 on 2021-12-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfmotors', '0009_auto_20211222_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(default='AAA', max_length=100),
        ),
    ]
