# Generated by Django 3.2.5 on 2022-02-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=30, verbose_name='Metodo de Pago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('cobrador', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.cobrador')),
                ('cuota', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='credito.cuota')),
                ('metodo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.metodopago')),
                ('tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.tipopago')),
            ],
        ),
    ]
