# Generated by Django 3.2.5 on 2021-07-21 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='credito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='credito.credito'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(),
        ),
    ]
