# Generated by Django 3.2.5 on 2022-04-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_alter_mora_cuota'),
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuota_pago', to='credito.cuota'),
        ),
    ]
