# Generated by Django 3.2 on 2021-10-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_auto_20210721_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.CharField(default='inserte descripcion del pago', max_length=300),
        ),
        migrations.AddField(
            model_name='pago',
            name='cobrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.cobrador'),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.metodopago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pago.tipopago'),
        ),
    ]
