# Generated by Django 3.2 on 2021-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_auto_20211012_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='metodo_pago',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='tipo_pago',
            field=models.CharField(max_length=30),
        ),
    ]
