# Generated by Django 3.2 on 2021-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_auto_20211012_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='metodo_pago',
            field=models.CharField(max_length=30, verbose_name='Metodo de Pago'),
        ),
    ]
