# Generated by Django 3.2 on 2021-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0005_alter_metodopago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
