# Generated by Django 3.2 on 2021-10-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0009_cuota_amortizacion'),
        ('pago', '0006_alter_pago_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='credito',
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='credito.cuota'),
        ),
    ]
