# Generated by Django 3.2.5 on 2021-12-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pago', '0007_auto_20211018_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('operacion', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=10)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('referencia', models.TextField(max_length=100)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cambio.activo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pago.cobrador')),
            ],
        ),
    ]
