# Generated by Django 3.2.5 on 2021-12-22 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncambio',
            name='activo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cambio.activo'),
        ),
    ]
