# Generated by Django 3.2.5 on 2021-12-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0002_alter_operacioncambio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacioncambio',
            name='comision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operacioncambio',
            name='referencia',
            field=models.TextField(max_length=200),
        ),
    ]
