# Generated by Django 3.2.5 on 2021-12-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambio', '0003_auto_20211222_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioncambio',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
